package ch12;

public class ExceptionEx1 {
    public static void main(String[] args) {

        String[] names =  {"Kim", "Lee", "Park", "Choi"};
        System.out.println(names[4]);
        System.out.println("프로그램 수행 완료");



    }
}
